export const SIGNUP_STUDENT=`SIGNUP_STUDENT`
export const SIGNUP_SCHOOL=`SIGNUP_SCHOOL`
export const GET_LIST_STUDENT=`GET_LIST_STUDENT`

export const SIGNIN_STUDENT=`SIGNIN_STUDENT`
export const GET_PROFILE=`GET_PROFILE`

export const PROFILE_ERR=`PROFILE_ERR`
export const SIGNUP_STUDENT_ERR=`SIGNUP_STUDENT_ERR`
export const SIGNIN_USER=`SIGNIN_USER`
export const SIGNIN_USER_ERR=`SIGNIN_USER_ERR`

export const GET_SCHOOL_PAGE=`GET_SCHOOL_PAGE`

export const PAGE_ERR=`PAGE_ERR`
export const UPDATE_SCHOOL=`UPDATE_SCHOOL`
export const UPDATE_STUDENT=`UPDATE_STUDENT`
export const ADD_COMMENT=`ADD_COMMENT`;
export const UPDATE_STUDENT_ERR=`UPDATE_STUDENT_ERR`
export const REMOVE_ERR_AUTH=`REMOVE_ERR_AUTH`